"""initial_migration

Revision ID: c4f2e6989355
Revises: 
Create Date: 2026-07-31 16:14:43.881549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f2e6989355'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_scanner_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('match_pattern', sa.String(length=1024), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plugins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('hook_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('repeater_tabs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upstream_proxies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('host', sa.String(length=512), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=512), nullable=True),
    sa.Column('auth_enabled', sa.Boolean(), nullable=False),
    sa.Column('dns_resolution', sa.String(length=16), nullable=False),
    sa.Column('scope_only', sa.Boolean(), nullable=False),
    sa.Column('exclude_hosts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clickbandit_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_url', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('layers', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_discovery_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('wordlist_path', sa.Text(), nullable=True),
    sa.Column('discovered_items', sa.JSON(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('completed_requests', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cookie_jar',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('secure', sa.Boolean(), nullable=False),
    sa.Column('http_only', sa.Boolean(), nullable=False),
    sa.Column('same_site', sa.String(length=32), nullable=True),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cookie_jar_domain'), 'cookie_jar', ['domain'], unique=False)
    op.create_table('interceptor_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('intercept_on_match', sa.Boolean(), nullable=False),
    sa.Column('match_type', sa.String(length=32), nullable=True),
    sa.Column('match_pattern', sa.Text(), nullable=True),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_replace_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('match_pattern', sa.Text(), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.Column('replacement', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repeater_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tab_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['tab_id'], ['repeater_tabs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('host', sa.String(length=512), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('http_version', sa.String(length=8), nullable=False),
    sa.Column('request_headers', sa.JSON(), nullable=False),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('request_body_binary', sa.LargeBinary(), nullable=True),
    sa.Column('is_body_truncated', sa.Boolean(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_reason', sa.String(length=128), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_body_binary', sa.LargeBinary(), nullable=True),
    sa.Column('response_content_type', sa.String(length=256), nullable=True),
    sa.Column('response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('api_type', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tls_version', sa.String(length=16), nullable=True),
    sa.Column('tls_cipher', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_host'), 'requests', ['host'], unique=False)
    op.create_index('ix_requests_host_method', 'requests', ['host', 'method'], unique=False)
    op.create_index('ix_requests_req_headers', 'requests', ['request_headers'], unique=False)
    op.create_index('ix_requests_resp_headers', 'requests', ['response_headers'], unique=False)
    op.create_index(op.f('ix_requests_response_status'), 'requests', ['response_status'], unique=False)
    op.create_index('ix_requests_session_timestamp', 'requests', ['session_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_requests_timestamp'), 'requests', ['timestamp'], unique=False)
    op.create_table('scan_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('scan_type', sa.String(length=16), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_handling_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_scope_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=16), nullable=False),
    sa.Column('pattern', sa.String(length=512), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.Column('match_domain', sa.Boolean(), nullable=False),
    sa.Column('protocols', sa.JSON(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparer_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('left_request_id', sa.Uuid(), nullable=True),
    sa.Column('right_request_id', sa.Uuid(), nullable=True),
    sa.Column('left_type', sa.String(length=16), nullable=False),
    sa.Column('right_type', sa.String(length=16), nullable=False),
    sa.Column('left_content', sa.Text(), nullable=True),
    sa.Column('right_content', sa.Text(), nullable=True),
    sa.Column('left_label', sa.String(length=255), nullable=True),
    sa.Column('right_label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['left_request_id'], ['requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['right_request_id'], ['requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severityenum'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('cwe', sa.String(length=32), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_findings_session_severity', 'findings', ['session_id', 'severity'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_table('fuzz_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('base_request_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_template', sa.Text(), nullable=False),
    sa.Column('attack_type', sa.String(length=16), nullable=False),
    sa.Column('wordlist_name', sa.String(length=255), nullable=False),
    sa.Column('wordlist_path', sa.Text(), nullable=True),
    sa.Column('positions', sa.JSON(), nullable=False),
    sa.Column('grep_matches', sa.JSON(), nullable=False),
    sa.Column('extractors', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('completed_requests', sa.Integer(), nullable=False),
    sa.Column('rate_limit_rps', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['base_request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intercepted_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('modified_method', sa.String(length=16), nullable=True),
    sa.Column('modified_url', sa.Text(), nullable=True),
    sa.Column('modified_headers', sa.JSON(), nullable=True),
    sa.Column('modified_body', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizer_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('websocket_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('is_binary', sa.Boolean(), nullable=False),
    sa.Column('payload_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collaborator_interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('interaction_type', sa.Enum('DNS', 'HTTP', 'HTTPS', name='interactiontypeenum'), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('resolved_to_finding', sa.Boolean(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('query_type', sa.String(length=16), nullable=True),
    sa.Column('query_name', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborator_interactions_token'), 'collaborator_interactions', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collaborator_interactions_token'), table_name='collaborator_interactions')
    op.drop_table('collaborator_interactions')
    op.drop_table('websocket_messages')
    op.drop_table('organizer_items')
    op.drop_table('intercepted_items')
    op.drop_table('fuzz_jobs')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index('ix_findings_session_severity', table_name='findings')
    op.drop_table('findings')
    op.drop_table('comparer_items')
    op.drop_table('target_scope_rules')
    op.drop_table('session_handling_rules')
    op.drop_table('scan_jobs')
    op.drop_index(op.f('ix_requests_timestamp'), table_name='requests')
    op.drop_index('ix_requests_session_timestamp', table_name='requests')
    op.drop_index(op.f('ix_requests_response_status'), table_name='requests')
    op.drop_index('ix_requests_resp_headers', table_name='requests')
    op.drop_index('ix_requests_req_headers', table_name='requests')
    op.drop_index('ix_requests_host_method', table_name='requests')
    op.drop_index(op.f('ix_requests_host'), table_name='requests')
    op.drop_table('requests')
    op.drop_table('repeater_history')
    op.drop_table('projects')
    op.drop_table('match_replace_rules')
    op.drop_table('interceptor_rules')
    op.drop_index(op.f('ix_cookie_jar_domain'), table_name='cookie_jar')
    op.drop_table('cookie_jar')
    op.drop_table('content_discovery_jobs')
    op.drop_table('clickbandit_configs')
    op.drop_table('upstream_proxies')
    op.drop_table('sessions')
    op.drop_table('repeater_tabs')
    op.drop_table('plugins')
    op.drop_table('custom_scanner_checks')
    # ### end Alembic commands ###
